# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {filemgmt 20-1318}  -suppress 
set_msg_config  -ruleid {10}  -id {DRC 23-20}  -suppress 
set_msg_config  -ruleid {11}  -id {Place 30-879}  -suppress 
set_msg_config  -ruleid {12}  -id {Place 30-574}  -suppress 
set_msg_config  -ruleid {2}  -id {Project 1-486}  -suppress 
set_msg_config  -ruleid {3}  -id {DRC 23-20}  -string {{WARNING: [DRC 23-20] Rule violation (CKLD-2) Clock Net has IO Driver, not a Clock Buf, and/or non-Clock loads - Clock net btnC_IBUF is directly driven by an IO rather than a Clock Buffer or may be an IO driving a mix of Clock Buffer and non-Clock loads. This connectivity should be reviewed and corrected as appropriate. Driver(s): btnC_IBUF_inst/O}}  -suppress 
set_msg_config  -ruleid {4}  -id {Place 30-574}  -string {{WARNING: [Place 30-574] Poor placement for routing between an IO pin and BUFG. This is normally an ERROR but the CLOCK_DEDICATED_ROUTE constraint is set to FALSE allowing your design to continue. The use of this override is highly discouraged as it may lead to very poor timing results. It is recommended that this error condition be corrected in the design.

	btnC_IBUF_inst (IBUF.O) is locked to IOB_X0Y13
	 and btnC_IBUF_BUFG_inst (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y1
Resolution: Poor placement of an IO pin and a BUFG has resulted in the router using a non-dedicated path between the two.  There are several things that could trigger this DRC, each of which can cause unpredictable clock insertion delays that result in poor timing.  This DRC could be caused by any of the following: (a) a clock port was placed on a pin that is not a CCIO-pin (b)the BUFG has not been placed in the same half of the device or SLR as the CCIO-pin (c) a single ended clock has been placed on the N-Side of a differential pair CCIO-pin.}}  -suppress 
set_msg_config  -ruleid {5}  -id {DRC 23-20}  -string {{WARNING: [DRC 23-20] Rule violation (PLCK-12) Clock Placer Checks - Poor placement for routing between an IO pin and BUFG. 
Resolution: Poor placement of an IO pin and a BUFG has resulted in the router using a non-dedicated path between the two.  There are several things that could trigger this DRC, each of which can cause unpredictable clock insertion delays that result in poor timing.  This DRC could be caused by any of the following: (a) a clock port was placed on a pin that is not a CCIO-pin (b)the BUFG has not been placed in the same half of the device or SLR as the CCIO-pin (c) a single ended clock has been placed on the N-Side of a differential pair CCIO-pin.
 This is normally an ERROR but the CLOCK_DEDICATED_ROUTE constraint is set to FALSE allowing your design to continue. The use of this override is highly discouraged as it may lead to very poor timing results. It is recommended that this error condition be corrected in the design.

	btnC_IBUF_inst (IBUF.O) is locked to U18
	btnC_IBUF_BUFG_inst (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y1}}  -suppress 
set_msg_config  -ruleid {6}  -id {Synth 8-3332}  -string {{WARNING: [Synth 8-3332] Sequential element (main_cnc/duck1_ctl/x_reg[0]) is unused and will be removed from module vga_example.}}  -suppress 
set_msg_config  -ruleid {7}  -id {Synth 8-3332}  -suppress 
set_msg_config  -ruleid {8}  -id {Synth 8-3331}  -suppress 
set_msg_config  -ruleid {9}  -id {Place 30-568}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet {{c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property is_locked true [get_files {{c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top clk_wiz_0 -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all clk_wiz_0_

write_checkpoint -force -noxdef clk_wiz_0.dcp

catch { report_utilization -file clk_wiz_0_utilization_synth.rpt -pb clk_wiz_0_utilization_synth.pb }

if { [catch {
  file copy -force {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp} {c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub {c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub {c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim {c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim {c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.vhdl}
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.ip_user_files/ip/clk_wiz_0}]} {
  catch { 
    file copy -force {{c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.v}} {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.ip_user_files/ip/clk_wiz_0}
  }
}

if {[file isdir {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.ip_user_files/ip/clk_wiz_0}]} {
  catch { 
    file copy -force {{c:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_stub.vhdl}} {C:/Users/Kiteu/OneDrive/UEC/Duck Hunt/vivado/Duck_Hunt.ip_user_files/ip/clk_wiz_0}
  }
}
